### ISSUE TITLE
AutoSpecOnAFK: fix timer working on Pause

### ISSUE THREAD

**Issue by StarterX4** [Krevik/Kether.pl-L4D2-Server#37]

**Comment by Krevik** [comment]
1. Change mechanism of the plugin to work the same way as readyup detects afking players (timer works a bit different here I think)
2. Use the forward/native function provided by readyup plugin to detect afk players and their afking time only while player isInReady (bool)

**Comment by StarterX4** [comment]
Succeeded by VoteToSpec (#9).
