### ISSUE TITLE
Tiebreaker bonus

### ISSUE THREAD

**Issue by Murzysko** [Krevik/Kether.pl-L4D2-Server#38]
[piątek, 00:08]
nara:
	Tiebreaker bonus should work only when both teams have the same amount of points, including bonus points.

**Comment by Krevik** [comment]
L4D2 mechanism of using tiebreaker bonus is hard-coded into the game code -> I am not sure if it's possible to anyhow modify it's behavior. It might be possible to affect the behavior by temporal altering actual score of the team at given map but it will probable be messy and buggy way to achieve such effect.
TODO: Check for alliedmodders plugins if there's a better way to do it.

**Comment by Murzysko** [comment]
In that case is it be better to completely delete tiebreaker bonus?

**Comment by Krevik** [comment]
@Murzysko could you please make a poll on our steam community chat what do they want to do with this issue and later give here in comment a screenshot from that voting?

**Comment by Murzysko** [comment]
![image](https://user-images.githubusercontent.com/93777590/184404629-ae55283c-ba81-461b-9473-1bf9f857963d.png)

**Comment by Krevik** [comment]
Fixed with @https://github.com/Krevik/Kether.pl-L4D2-Server/commit/ce7673760f278bce10fa67c270f3936f2473bd8f
