### ISSUE TITLE
Zmiany dot. statystyk mvp

### ISSUE THREAD

**Issue by Murzysko** [Krevik/Kether.pl-L4D2-Server#4]
W tej kwestii usunąłbym wliczanie obrażeń ff zadawanych leżącym ocalałym, zaburza rzeczywisty wymiar ff i nie ma większego znaczenia dla gry.

Ponadto rozbudowałbym statystyki mvp, podobnie jak to jest na zm, sami możemy dodać własne statystyki. Jak choćby już dodane revive, ale to akurat usunąłbym z wyświetlania na czacie, wtedy za duży chaos się tworzy i nie widać czas całości statystyk na czacie gdy ktoś ma bardzo długi nick, jak Saint.

Do przykładowych statystyk można by dodać sumy "cutów", "popów", "skeetów kamieni i hunterów" i całościowych statystyk SI, CI i FF poszczególnych członków drużyn - ale to bym zostawił do przemyślenia, bo wydaje mi się że często niektórzy mają poniżej 10% czegokolwiek, więc to byłoby trochę meh uwypuklanie czyjegoś braku zaangażowania w grę czy w ogóle umiejętności.

**Comment by Krevik** [comment]
Planuję wgrać rozbudowane statystyki te same co są na zm, jednak problem jest taki ze aktualnie ten plugin u nas srednio dziala (prawdopodobnie zrodlo problemu jest w tym samym miejscu co problem z latającymi propami tanka czy nie działającym spawn orderem). Co do nowych pozycji to niestety zwykle detekcja takich eventów jest dosyć skomplikowana i problematyczna, dlatego na tą chwilę nie planuję dodawać nowych, dodatkowych statystyk poza tymi co są na zm. Co do FF od ognia to zgadzam się jak najbardziej i trzeba będzie to zrobić.

**Comment by Krevik** [comment]
Dodano playstats (konsola)
