### ISSUE TITLE
Tank pass missing on 3v3 Nextmod matchmode

### ISSUE THREAD

**Issue by StarterX4** [Krevik/Kether.pl-L4D2-Server#51]
probably plugin not loaded in

**Comment by Krevik** [comment]
Tank pass is loaded only on kether default config. I didn't install this plugin on any other matchmode, as tank pass requires several plugin modifications to be fully functionable - as far as I remember readyup is the most important one. Therefore it is not a bug, I would consider it more as a suggestion.

**Comment by Krevik** [comment]
As other matchmodes are not and won't be important part of this repo, I am gonna close it. Upkeep of such changes with the fact of frequent Sir's updates would be tough.
