### ISSUE TITLE
[BUG] Remove useless rcon_password config

### ISSUE THREAD

**Issue by V3nilla** [Krevik/Kether.pl-L4D2-Server#63]
**Describe the bug**
This config is not needed in any way

We can just did this in all server.cfg configs:
`rcon_password "DontForgetToSetYour0wnP4ssword"        	 // Rcon password, used for remote access mostly.`

Instead of this:
```
//rcon_password ""        	 // Rcon password, used for remote access mostly.
exec rcon_password.cfg       // Separate config for rcon_password cvar
```

**Comment by StarterX4** [comment]
That's easier for us to not have two versions of the same configs every time we would change something in there.
Though I left that former commented out in case someone would wish to have theirs password in the main config.
